# SPDX-License-Identifier: GPL-3.0-only

# Source
source = ./keybindings.conf
source = ./windowrules.conf
source = ./theme.conf
source = ./animations.conf
source = ./misc.conf
source = ./startup.conf # Should be last

