# SPDX-License-Identifier: GPL-3.0-only

# Variables
$mod = SUPER

# Programs
bind = $mod, T, exec, uwsm app -- $TERMINAL # Open terminal
bind = $mod, B, exec, uwsm app -- $BROWSER # Open browser
bind = $mod, E, exec, uwsm app -- kitty $FILE_EXPLORER # Open file explorer
bind = $mod, C, exec, uwsm app -- cliphist list | rofi -dmenu | cliphist decode | wl-copy # Copy an item from the clipboard history
bind = $mod, V, exec, uwsm app -- rofimoji # Emojis
bind = $mod, W, exec, uwsm app -- killall waybar || waybar # Toggle waybar
bind = $mod Ctrl Shift, L, exec, uwsm app -- wlogout # Open power menu
bind = $mod, N, exec, uwsm app -- swaync-client -t # Open notification menu
bind = $mod, P, exec, uwsm app -- hyprpicker --autocopy --notify # Pick a color from the screen
bind = $mod, A, exec, hyprlauncher # Open app launch menu
bind = $mod Ctrl, L, exec, uwsm app -- hyprlock # Lock session
bind = $mod, Tab, exec, uwsm app -- snappy-switcher next # App switch menu
bind = $mod Shift, Tab, exec, uwsm app -- snappy-switcher prev # App switch menu
bind = Ctrl Shift, Escape, exec, uwsm app -- kitty btop # Task manager



# Windows

## Switch focus
### Same-desktop
bind = $mod, H, movefocus, l
bind = $mod, J, movefocus, d
bind = $mod, K, movefocus, u
bind = $mod, L, movefocus, r
### Cross-desktop
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

## Move
### Same-desktop
bind = $mod Shift, H, swapwindow, l
bind = $mod Shift, J, swapwindow, d
bind = $mod Shift, K, swapwindow, u
bind = $mod Shift, L, swapwindow, r
### Cross-desktop
bind = $mod Shift, 1, movetoworkspace, 1
bind = $mod Shift, 2, movetoworkspace, 2
bind = $mod Shift, 3, movetoworkspace, 3
bind = $mod Shift, 4, movetoworkspace, 4
bind = $mod Shift, 5, movetoworkspace, 5
bind = $mod Shift, 6, movetoworkspace, 6
bind = $mod Shift, 7, movetoworkspace, 7
bind = $mod Shift, 8, movetoworkspace, 8
bind = $mod Shift, 9, movetoworkspace, 9
bind = $mod Shift, 0, movetoworkspace, 10

## Toggle
bind = $mod, F, fullscreen, 0
bind = $mod, Space, togglefloating

## Resize
bind = $mod, R, exec, notify-send -a "Hyprland" "Submap" "Resize mode"
bind = $mod, R, submap, resize
submap = resize
# Shift is always to reduce the size
binde = ,		H,	exec, ~/.config/hypr/scripts/top_left_resize.sh -10 0	# Resize left edge to the left
binde = Shift,	H,	exec, ~/.config/hypr/scripts/top_left_resize.sh 10 0	# Resize left edge to the right
binde = ,		J,	resizeactive, 0 10										# Resize bottom edge down
binde = Shift,	J,	resizeactive, 0 -10										# Resize bottom edge up
binde =	,		K,	exec, ~/.config/hypr/scripts/top_left_resize.sh 0 -10	# Resize top edge up
binde = Shift,	K,	exec, ~/.config/hypr/scripts/top_left_resize.sh 0 10	# Resize top edge down
binde = ,		L,	resizeactive, 10 0										# Resize right edge to the right
binde = Shift,	L,	resizeactive, -10 0										# Resize right edge to the left
bind = , Escape, exec, notify-send -a "Hyprland" "Submap" "Normal mode"
bind = , Escape, submap, reset
submap = reset
## Mouse
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow



# Other
bind = $mod, Q, exec, hyprctl dispatch killactive
bind = $mod Shift, Q, exec, hyprctl dispatch forcekillactive
