# SPDX-License-Identifier: GPL-3.0-only

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 3
	col.active_border = rgba(0a0113ff) rgba(98295bff) rgba(682092ff) rgba(4a51a3ff) rgba(b53fb9ff) rgba(9f58a4ff) rgba(6fd7c3ff) rgba(e0bee4ff) rgba(9c859fff) rgba(98295bff) 45deg
    col.inactive_border = rgba(0A1010ff) rgba(1A2525ff) 45deg
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 10
    blur {
        enabled = yes
        size = 4
        passes = 2
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
    shadow {
        enabled = false
    }
}

