# SPDX-License-Identifier: GPL-3.0-only

# Transparency
windowrule {
	name = transparency
	match:class = (?i)(firefox|steam)
	opacity = 0.9 0.8 1.0
}
windowrule {
	name = transparency-kitty
	match:class = (?i)kitty
	opacity = 0.8 0.7 0.1
}
windowrule {
	name = transparency-rofi
	match:class = (?i)rofi
	opacity = 0.5 1 0.1
}

# Fullscreen
windowrule {
	name = floating-wallpaper_picker
	match:class = wallpaper_picker
	fullscreen = on
}
