# SPDX-License-Identifier: GPL-3.0-only
# NOTE: This file is automatically managed by `scripts/change_wallpaper.zsh`! Please use that to change your wallpaper.

preload = ~/.config/hypr/wallpapers/set_your_wallpaper_here.png

wallpaper {
	monitor =
	path = ~/.config/hypr/wallpapers/set_your_wallpaper_here.png
}

splash = false

