# SPDX-License-Identifier: GPL-3.0-only

exec-once = uwsm app -- kitty --title Reminder zsh -c "Modify ~/.config/hypr/startup.conf to set your startup programs. And also to remove this warning. && sleep infinity"
