# SPDX-License-Identifier: GPL-3.0-only

preload = ~/.config/hypr/wallpapers/set_your_wallpaper_here.png

wallpaper {
	monitor =
	path = ~/.config/hypr/wallpapers/set_your_wallpaper_here.png
}

splash = false

